baseurl = "https://blog.fruitraccoon.com/"
languageCode = "en-au"
title = "Jono's Blog"
theme = "hugo-steam-theme"

disqusShortname = ""
# Enable Google Analytics be inserting your tracking code
googleAnalytics = ""

# Number of posts per page
paginate = 10

[params]
	title = "Jono's Blog"
	subtitle = "A place for things that have caught my attention"
	copyright = ""

	# You can choose between green, orange, red and blue.
	themecolor = "blue"

	# Link custom assets relative to /static
	favicon   = "favicon.ico"
	customCSS = []
	customJS  = []

	# To provide some metadata for search engines and the about section in the footer
	# feel free to add a few information about you and your website.
	name = "Jono Job"
	bio = "your humble host for this small corner of the internet"
	description = "A place for things that have caught my attention"

	# Link your social networks (optional)
	location = ""
	twitter = ""
	linkedin = ""
	googleplus = ""
	facebook = ""
	instagram = ""
	github = "fruitraccoon"
	gitlab = ""
	bitbucket = ""

	# Customize or translate the strings
	keepReadingStr = "Keep reading"
	backtotopStr = "Back to top"
	shareStr = "Share"
	pageNotFoundTitle = "404 - Page not found"

	useSummaryIfNoDescription = true

[permalinks]
  posts = "/:year/:month/:slug/"

[blackfriday]
  hrefTargetBlank = true
  extension = ["footnotes"]
